name: PlayerTags
version: '${version}'
main: net.moonlar.playertags.PlayerTags
load: POSTWORLD
softdepend: [ PlaceholderAPI ]
authors: [ GiverPlay ]
description: A simple tags plugin
website: https://moonlar.net
commands:
  playertags:
    description: 'Main plugin command'
    aliases: [pt, ptags, tags]